# Generated by Django 4.2.6 on 2023-10-24 05:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_detailsale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailsale',
            options={'verbose_name': 'Detalle Venta', 'verbose_name_plural': 'Detalles Ventas'},
        ),
        migrations.RemoveField(
            model_name='detailsale',
            name='cant',
        ),
        migrations.RemoveField(
            model_name='detailsale',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='detailsale',
            name='delete_date',
        ),
        migrations.RemoveField(
            model_name='detailsale',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='detailsale',
            name='state',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='delete_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='state',
        ),
        migrations.AddField(
            model_name='detailsale',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.sale'),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
