# Generated by Django 4.2.6 on 2023-10-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_detailsale_options_remove_detailsale_cant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsale',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
