# Generated by Django 4.2.6 on 2023-11-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_detailsale_state_sale_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsale',
            name='state',
        ),
        migrations.AddField(
            model_name='sale',
            name='cancel',
            field=models.BooleanField(default=True, verbose_name='Cancelado'),
        ),
    ]
